---
cloudpipe:
  build: .
  links:
  - mongo
  - authstore
  environment:
    PIPE_ADMINNAME: admin
    PIPE_ADMINKEY: 12345
    PIPE_LOGLEVEL: debug
    PIPE_LOGCOLORS: true
    PIPE_CACERT: /certificates/ca.pem
    PIPE_CERT: /certificates/cloudpipe-cert.pem
    PIPE_KEY: /certificates/cloudpipe-key.pem
    PIPE_AUTHSERVICE: https://authstore:9001/v1
  ports:
  - "8000:8000"
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "certificates:/certificates"
authstore:
  image: cloudpipe/auth-store
  links:
  - mongo
  environment:
    AUTH_LOGLEVEL: debug
    AUTH_LOGCOLORS: true
    AUTH_INTERNALCACERT: /certificates/ca.pem
    AUTH_INTERNALCERT: /certificates/auth-store-cert.pem
    AUTH_INTERNALKEY: /certificates/auth-store-key.pem
    AUTH_EXTERNALCERT: /certificates/external-cert.pem
    AUTH_EXTERNALKEY: /certificates/external-key.pem
  expose:
  - "9001"
  ports:
  - "9000:9000"
  volumes:
  - "certificates:/certificates"
mongo:
  image: mongo:2.6
dummyuserimage:
  image: cloudpipe/runner-py2
  command: "echo 'User image loaded'"
