#!/bin/bash
#
# Open the Mongo CLI on a running mongo container.

exec docker run -it --link rhocloud_mongo_1:mongo --rm mongo:2.8 \
  sh -c 'exec mongo "$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/rho"'
