#!/bin/bash

set -e

ROOT=$(dirname $0)/..
cd ${ROOT}

docker-compose build >/dev/null 2>&1 || echo "compose build failed!"

exec docker-compose run --no-deps --rm cloudpipe go test github.com/cloudpipe/cloudpipe/... $@
