#!/bin/bash

ROOT=$(dirname $0)/..
cd ${ROOT}

fig build

echo ">> cloudpipe tests"

fig run --rm cloudpipe go test github.com/cloudpipe/cloudpipe/...
STATUS=$?

if [ "${STATUS}" != "0" ]; then
  echo "!! cloudpipe tests are failing"
else
  echo "<< cloudpipe tests passed"
fi
